// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: zmk/key_usage/key_usage.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "zmk.key_usage";

/**
 * Ask the keyboard for every non-zero counter. The counters themselves are
 * streamed back as StatsChunk notifications.
 */
export interface GetStatsRequest {
}

/** Drop every counter, both in RAM and in persistent storage. */
export interface ClearStatsRequest {
}

/** Flush pending counters to persistent storage right now. */
export interface SaveStatsRequest {
}

/** Press count for one (layer, key position) pair. */
export interface PositionEntry {
  layer: number;
  position: number;
  count: number;
}

/** Press count for one HID keycode actually sent to the host. */
export interface KeycodeEntry {
  usagePage: number;
  keycode: number;
  count: number;
}

export interface StatsMetadata {
  /** Total presses counted since the last clear. */
  totalPresses: number;
  /** Number of layers the firmware tracks separately. */
  maxLayers: number;
  /** Number of key positions the firmware tracks. */
  maxPositions: number;
  /** Highest tracked HID keycode, 0 when keycode tracking is disabled. */
  maxKeycode: number;
}

export interface GetStatsResponse {
  metadata?: StatsMetadata | undefined;
}

export interface ClearStatsResponse {
}

export interface SaveStatsResponse {
}

export interface Request {
  getStats?: GetStatsRequest | undefined;
  clearStats?: ClearStatsRequest | undefined;
  saveStats?: SaveStatsRequest | undefined;
}

export interface ErrorResponse {
  message: string;
}

export interface Response {
  error?: ErrorResponse | undefined;
  getStats?: GetStatsResponse | undefined;
  clearStats?: ClearStatsResponse | undefined;
  saveStats?: SaveStatsResponse | undefined;
}

/** One chunk of streamed counters. */
export interface StatsChunk {
  positions: PositionEntry[];
  keycodes: KeycodeEntry[];
  /** True on the final chunk of a stream. */
  isLast: boolean;
  /** 0-based index of this chunk within the stream. */
  chunkIndex: number;
}

export interface Notification {
  stats?: StatsChunk | undefined;
}

function createBaseGetStatsRequest(): GetStatsRequest {
  return {};
}

export const GetStatsRequest: MessageFns<GetStatsRequest> = {
  encode(_: GetStatsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStatsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStatsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetStatsRequest>): GetStatsRequest {
    return GetStatsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetStatsRequest>): GetStatsRequest {
    const message = createBaseGetStatsRequest();
    return message;
  },
};

function createBaseClearStatsRequest(): ClearStatsRequest {
  return {};
}

export const ClearStatsRequest: MessageFns<ClearStatsRequest> = {
  encode(_: ClearStatsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClearStatsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClearStatsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ClearStatsRequest>): ClearStatsRequest {
    return ClearStatsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ClearStatsRequest>): ClearStatsRequest {
    const message = createBaseClearStatsRequest();
    return message;
  },
};

function createBaseSaveStatsRequest(): SaveStatsRequest {
  return {};
}

export const SaveStatsRequest: MessageFns<SaveStatsRequest> = {
  encode(_: SaveStatsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SaveStatsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSaveStatsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SaveStatsRequest>): SaveStatsRequest {
    return SaveStatsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<SaveStatsRequest>): SaveStatsRequest {
    const message = createBaseSaveStatsRequest();
    return message;
  },
};

function createBasePositionEntry(): PositionEntry {
  return { layer: 0, position: 0, count: 0 };
}

export const PositionEntry: MessageFns<PositionEntry> = {
  encode(message: PositionEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.layer !== 0) {
      writer.uint32(8).uint32(message.layer);
    }
    if (message.position !== 0) {
      writer.uint32(16).uint32(message.position);
    }
    if (message.count !== 0) {
      writer.uint32(24).uint32(message.count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PositionEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePositionEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.layer = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.position = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.count = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<PositionEntry>): PositionEntry {
    return PositionEntry.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PositionEntry>): PositionEntry {
    const message = createBasePositionEntry();
    message.layer = object.layer ?? 0;
    message.position = object.position ?? 0;
    message.count = object.count ?? 0;
    return message;
  },
};

function createBaseKeycodeEntry(): KeycodeEntry {
  return { usagePage: 0, keycode: 0, count: 0 };
}

export const KeycodeEntry: MessageFns<KeycodeEntry> = {
  encode(message: KeycodeEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.usagePage !== 0) {
      writer.uint32(8).uint32(message.usagePage);
    }
    if (message.keycode !== 0) {
      writer.uint32(16).uint32(message.keycode);
    }
    if (message.count !== 0) {
      writer.uint32(24).uint32(message.count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KeycodeEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeycodeEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.usagePage = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.keycode = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.count = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<KeycodeEntry>): KeycodeEntry {
    return KeycodeEntry.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<KeycodeEntry>): KeycodeEntry {
    const message = createBaseKeycodeEntry();
    message.usagePage = object.usagePage ?? 0;
    message.keycode = object.keycode ?? 0;
    message.count = object.count ?? 0;
    return message;
  },
};

function createBaseStatsMetadata(): StatsMetadata {
  return { totalPresses: 0, maxLayers: 0, maxPositions: 0, maxKeycode: 0 };
}

export const StatsMetadata: MessageFns<StatsMetadata> = {
  encode(message: StatsMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalPresses !== 0) {
      writer.uint32(8).uint32(message.totalPresses);
    }
    if (message.maxLayers !== 0) {
      writer.uint32(16).uint32(message.maxLayers);
    }
    if (message.maxPositions !== 0) {
      writer.uint32(24).uint32(message.maxPositions);
    }
    if (message.maxKeycode !== 0) {
      writer.uint32(32).uint32(message.maxKeycode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatsMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatsMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.totalPresses = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.maxLayers = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxPositions = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.maxKeycode = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<StatsMetadata>): StatsMetadata {
    return StatsMetadata.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StatsMetadata>): StatsMetadata {
    const message = createBaseStatsMetadata();
    message.totalPresses = object.totalPresses ?? 0;
    message.maxLayers = object.maxLayers ?? 0;
    message.maxPositions = object.maxPositions ?? 0;
    message.maxKeycode = object.maxKeycode ?? 0;
    return message;
  },
};

function createBaseGetStatsResponse(): GetStatsResponse {
  return { metadata: undefined };
}

export const GetStatsResponse: MessageFns<GetStatsResponse> = {
  encode(message: GetStatsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.metadata !== undefined) {
      StatsMetadata.encode(message.metadata, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStatsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStatsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.metadata = StatsMetadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetStatsResponse>): GetStatsResponse {
    return GetStatsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetStatsResponse>): GetStatsResponse {
    const message = createBaseGetStatsResponse();
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? StatsMetadata.fromPartial(object.metadata)
      : undefined;
    return message;
  },
};

function createBaseClearStatsResponse(): ClearStatsResponse {
  return {};
}

export const ClearStatsResponse: MessageFns<ClearStatsResponse> = {
  encode(_: ClearStatsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClearStatsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClearStatsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ClearStatsResponse>): ClearStatsResponse {
    return ClearStatsResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ClearStatsResponse>): ClearStatsResponse {
    const message = createBaseClearStatsResponse();
    return message;
  },
};

function createBaseSaveStatsResponse(): SaveStatsResponse {
  return {};
}

export const SaveStatsResponse: MessageFns<SaveStatsResponse> = {
  encode(_: SaveStatsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SaveStatsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSaveStatsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SaveStatsResponse>): SaveStatsResponse {
    return SaveStatsResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<SaveStatsResponse>): SaveStatsResponse {
    const message = createBaseSaveStatsResponse();
    return message;
  },
};

function createBaseRequest(): Request {
  return { getStats: undefined, clearStats: undefined, saveStats: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.getStats !== undefined) {
      GetStatsRequest.encode(message.getStats, writer.uint32(10).fork()).join();
    }
    if (message.clearStats !== undefined) {
      ClearStatsRequest.encode(message.clearStats, writer.uint32(18).fork()).join();
    }
    if (message.saveStats !== undefined) {
      SaveStatsRequest.encode(message.saveStats, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.getStats = GetStatsRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clearStats = ClearStatsRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.saveStats = SaveStatsRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.getStats = (object.getStats !== undefined && object.getStats !== null)
      ? GetStatsRequest.fromPartial(object.getStats)
      : undefined;
    message.clearStats = (object.clearStats !== undefined && object.clearStats !== null)
      ? ClearStatsRequest.fromPartial(object.clearStats)
      : undefined;
    message.saveStats = (object.saveStats !== undefined && object.saveStats !== null)
      ? SaveStatsRequest.fromPartial(object.saveStats)
      : undefined;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseResponse(): Response {
  return { error: undefined, getStats: undefined, clearStats: undefined, saveStats: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.getStats !== undefined) {
      GetStatsResponse.encode(message.getStats, writer.uint32(18).fork()).join();
    }
    if (message.clearStats !== undefined) {
      ClearStatsResponse.encode(message.clearStats, writer.uint32(26).fork()).join();
    }
    if (message.saveStats !== undefined) {
      SaveStatsResponse.encode(message.saveStats, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getStats = GetStatsResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.clearStats = ClearStatsResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.saveStats = SaveStatsResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.getStats = (object.getStats !== undefined && object.getStats !== null)
      ? GetStatsResponse.fromPartial(object.getStats)
      : undefined;
    message.clearStats = (object.clearStats !== undefined && object.clearStats !== null)
      ? ClearStatsResponse.fromPartial(object.clearStats)
      : undefined;
    message.saveStats = (object.saveStats !== undefined && object.saveStats !== null)
      ? SaveStatsResponse.fromPartial(object.saveStats)
      : undefined;
    return message;
  },
};

function createBaseStatsChunk(): StatsChunk {
  return { positions: [], keycodes: [], isLast: false, chunkIndex: 0 };
}

export const StatsChunk: MessageFns<StatsChunk> = {
  encode(message: StatsChunk, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.positions) {
      PositionEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.keycodes) {
      KeycodeEntry.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.isLast !== false) {
      writer.uint32(24).bool(message.isLast);
    }
    if (message.chunkIndex !== 0) {
      writer.uint32(32).uint32(message.chunkIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatsChunk {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatsChunk();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.positions.push(PositionEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.keycodes.push(KeycodeEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isLast = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.chunkIndex = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<StatsChunk>): StatsChunk {
    return StatsChunk.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StatsChunk>): StatsChunk {
    const message = createBaseStatsChunk();
    message.positions = object.positions?.map((e) => PositionEntry.fromPartial(e)) || [];
    message.keycodes = object.keycodes?.map((e) => KeycodeEntry.fromPartial(e)) || [];
    message.isLast = object.isLast ?? false;
    message.chunkIndex = object.chunkIndex ?? 0;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { stats: undefined };
}

export const Notification: MessageFns<Notification> = {
  encode(message: Notification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stats !== undefined) {
      StatsChunk.encode(message.stats, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Notification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stats = StatsChunk.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Notification>): Notification {
    return Notification.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Notification>): Notification {
    const message = createBaseNotification();
    message.stats = (object.stats !== undefined && object.stats !== null)
      ? StatsChunk.fromPartial(object.stats)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
